diff --git a/Dockerfile.base b/Dockerfile.base
index 099e36d..1518386 100644
--- a/Dockerfile.base
+++ b/Dockerfile.base
@@ -16,6 +16,40 @@ RUN apt --yes install --no-install-recommends dotnet-sdk-10.0
 RUN apt --yes install --no-install-recommends npm
 RUN npm install --global yarn
 
+RUN apt --yes install --no-install-recommends openssh-server
+RUN apt --yes install --no-install-recommends cron
+RUN apt --yes install --no-install-recommends sudo
+RUN apt --yes install --no-install-recommends wget
+RUN apt --yes install --no-install-recommends postgresql
+RUN apt --yes install --no-install-recommends nginx
+RUN apt --yes install --no-install-recommends socat
+# for `killall` command
+RUN apt --yes install --no-install-recommends psmisc
+# for `make` command
+RUN apt --yes install --no-install-recommends build-essential
+
+# Pulumi CLI
+ARG PULUMI_VERSION=3.201.0
+RUN wget https://get.pulumi.com/releases/sdk/pulumi-v$PULUMI_VERSION-linux-x64.tar.gz --output-document=pulumi.tar.gz
+RUN tar --extract --gzip --verbose --file pulumi.tar.gz
+RUN rm pulumi.tar.gz
+RUN mv ./pulumi /usr/local/bin/pulumi
+RUN chmod +x /usr/local/bin/pulumi
+
+# Install Xray (use script in latest commit in XTLS/Xray-install repo as of writing this script)
+RUN wget https://raw.githubusercontent.com/XTLS/Xray-install/b7410c4e2fe2ed5c0ddca508eba2f4e42a91e1d2/install-release.sh
+RUN wget https://github.com/XTLS/Xray-core/releases/download/v25.9.11/Xray-linux-64.zip
+# install-release.sh will prompt to press any key with local install, so use "yes" command to simulate key press
+# temporarily disable pipefail because otherwise install-release.sh will fail the whole script because of these errors:
+# rm: cannot remove '/etc/systemd/system/xray.service.d/10-donot_touch_multi_conf.conf': No such file or directory
+# rm: cannot remove '/etc/systemd/system/xray@.service.d/10-donot_touch_multi_conf.conf': No such file or directory
+RUN chmod +x ./install-release.sh
+# install-release.sh will not fail trying to detect systemd if /.dockerenv file exists
+RUN touch /.dockerenv
+RUN yes | ./install-release.sh --local ./Xray-linux-64.zip
+RUN rm ./install-release.sh
+RUN rm ./Xray-linux-64.zip
+
 # cleanup apt cache to reduce img size & avoid unneeded files in the final layer
 RUN rm -rf /var/lib/apt/lists/*
 
